apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: molos
  app.kubernetes.io/part-of: molos-system

images:
  - name: ghcr.io/molos-app/molos
    newTag: latest
