apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: molos
  name: molos-data-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ./molos
    type: DirectoryOrCreate