apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: molos-data-pvc
spec:
  storageClassName: local-storage
  volumeName: molos-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
