apiVersion: v1
kind: Secret
metadata:
  namespace: molos
  name: molos-secrets
type: Opaque
stringData:
  better-auth-secret: 'super-secret-production-fallback-key-for-build-only-not-secure-for-runtime'