apiVersion: v1
kind: Service
metadata:
  name: molos-service
spec:
  selector:
    app: molos
  ports:
    - protocol: TCP
      port: 4173
      targetPort: 4173
      nodePort: 30173
  type: NodePort
